version: '2'
services:

    aata_arches:
      container_name: aata_arches
      command: run_aata
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - aata_arches-log:/arches/arches/logs
        - aata_arches-static:/static_root
      environment:
        - ARCHES_VERSION=master
        - PGUSERNAME=arches
        - PGPASSWORD=archespwd
        - PGDBNAME=arches
        - PGHOST=db
        - PGPORT=5432
        - COUCHDB_HOST=couchdb
        - COUCHDB_PORT=5984
        - COUCHDB_USER=admin
        - COUCHDB_PASS=password
        - ESHOST=elasticsearch
        - ESPORT=9200
        - ELASTICSEARCH_PREFIX=aata
        - DJANGO_MODE=DEV
        - DJANGO_DEBUG=True
        - DJANGO_REMOTE_DEBUG=False
        - DOMAIN_NAMES=localhost
        - TZ=PST
      ports:
        - '8000:8000'
      depends_on:
        - db
        - elasticsearch
        - couchdb

    nginx:
      container_name: nginx
      image: cvast/cvast-nginx:1.2.0
      restart: unless-stopped
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - aata_arches-static:/www/static
        - letsencrypt-acme-challenge:/var/www
        - letsencrypt:/etc/letsencrypt
      environment:
        - NGINX_PROXY_MODE=local
        - NGINX_PROTOCOL=http
        - LOCAL_PROXY_HOST=aata_arches
        - LOCAL_PROXY_PORT=8000
        - DOMAIN_NAMES=localhost
        - PUBLIC_MODE=False
        - TZ=PST
      depends_on:
        - aata_arches

    db:
      container_name: db
      build:
        context: .
        dockerfile: ./Dockerfile_postgis
      volumes:
          - postgres-data:/var/lib/postgresql/data
          - postgres-log:/var/log/postgresql
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=postgres
        - PGUSERNAME=arches
        - PGPASSWORD=archespwd
        - PGDBNAME=arches
        - POSTGRES_USER=postgres
        - TZ=PST

    pgadmin:
      container_name: pgadmin
      links:
        - db:postgres
      image: dpage/pgadmin4
      volumes:
        - pgadmin_data:/root/.pgadmin
      ports:
        - "5050:80"
      environment:
        - PGADMIN_DEFAULT_EMAIL=postgres
        - PGADMIN_DEFAULT_PASSWORD=postgres
      restart: unless-stopped

    elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      entrypoint:
        - elasticsearch
        - -Ehttp.port=9200
        - -Ehttp.cors.enabled=true
        - -Ehttp.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
        - -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        - -Ehttp.cors.allow-credentials=true
      user: elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - TZ=PST

    couchdb:
      container_name: couchdb
      image: couchdb:2.1.1
      ports:
        - "5984:5984"
      environment:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: password
      volumes:
        - couchdb-data:/usr/local/var/lib/couchdb
        - couchdb-log:/usr/local/var/log/couchdb

    letsencrypt:
      container_name: letsencrypt
      image: cvast/cvast-letsencrypt:1.1
      volumes:
        - letsencrypt-acme-challenge:/var/www
        - letsencrypt:/etc/letsencrypt
        - letsencrypt-log:/var/log/letsencrypt
      command: get_certificate
      environment:
        - MODE=regular
        - LETSENCRYPT_EMAIL=info@example.com
        - DOMAIN_NAMES=localhost
        - PRODUCTION_MODE=False
        - PERSISTENT_MODE=True
        - TZ=PST


volumes:
    aata_arches-log:
    aata_arches-static:
    couchdb-data:
    couchdb-log:
    postgres-data:
    postgres-log:
    elasticsearch-data:
    letsencrypt:
    letsencrypt-log:
    letsencrypt-acme-challenge:
    pgadmin_data:
